import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'data', 'expansions');
const OUT_FILE = path.join(ROOT, 'lib', 'data', 'expansions.generated.ts');

type RawCard = {
  id: string;
  name: string;
  type: 'Gem' | 'Relic' | 'Spell';
  cost: number;
  effect?: string;
  keywords?: string[];
};

type RawExpansion = {
  id: string;
  name: string;
  abbr?: string;
  cards: RawCard[];
  mages?: unknown[];
  nemeses?: unknown[];
};

const VALID_TYPES = new Set(['Gem', 'Relic', 'Spell']);

function validateExpansion(raw: unknown, file: string): RawExpansion {
  if (!raw || typeof raw !== 'object') {
    throw new Error(`${file}: ルートはオブジェクトである必要があります`);
  }
  const r = raw as Record<string, unknown>;
  if (typeof r.id !== 'string') throw new Error(`${file}: id (string) が必要`);
  if (typeof r.name !== 'string') throw new Error(`${file}: name (string) が必要`);
  if (!Array.isArray(r.cards)) throw new Error(`${file}: cards (array) が必要`);

  const seenIds = new Set<string>();
  const cards: RawCard[] = r.cards.map((c, idx) => {
    if (!c || typeof c !== 'object') {
      throw new Error(`${file}: cards[${idx}] はオブジェクト`);
    }
    const card = c as Record<string, unknown>;
    if (typeof card.id !== 'string') throw new Error(`${file}: cards[${idx}].id (string)`);
    if (typeof card.name !== 'string') throw new Error(`${file}: cards[${idx}].name (string)`);
    if (typeof card.type !== 'string' || !VALID_TYPES.has(card.type)) {
      throw new Error(`${file}: cards[${idx}].type は Gem/Relic/Spell のいずれか`);
    }
    if (typeof card.cost !== 'number' || !Number.isFinite(card.cost)) {
      throw new Error(`${file}: cards[${idx}].cost (number)`);
    }
    if (seenIds.has(card.id)) {
      throw new Error(`${file}: 拡張内で id が重複: ${card.id}`);
    }
    seenIds.add(card.id);
    return {
      id: card.id,
      name: card.name,
      type: card.type as RawCard['type'],
      cost: card.cost,
      effect: typeof card.effect === 'string' ? card.effect : undefined,
      keywords: Array.isArray(card.keywords)
        ? card.keywords.filter((k): k is string => typeof k === 'string')
        : undefined,
    };
  });

  return {
    id: r.id,
    name: r.name,
    abbr: typeof r.abbr === 'string' ? r.abbr : undefined,
    cards,
    mages: Array.isArray(r.mages) ? r.mages : [],
    nemeses: Array.isArray(r.nemeses) ? r.nemeses : [],
  };
}

function main() {
  const files = readdirSync(SRC_DIR).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'));
  if (files.length === 0) {
    throw new Error(`${SRC_DIR} に YAML ファイルがありません`);
  }

  const expansions = files.map((f) => {
    const text = readFileSync(path.join(SRC_DIR, f), 'utf8');
    const parsed = yaml.load(text);
    return validateExpansion(parsed, f);
  });

  const seenExpIds = new Set<string>();
  for (const e of expansions) {
    if (seenExpIds.has(e.id)) {
      throw new Error(`拡張 id が重複: ${e.id}`);
    }
    seenExpIds.add(e.id);
  }

  const data = expansions.map((e) => ({
    id: e.id,
    name: e.name,
    abbr: e.abbr,
    cards: e.cards.map((c) => ({
      id: `${e.id}:${c.id}`,
      expansionId: e.id,
      name: c.name,
      type: c.type,
      cost: c.cost,
      effect: c.effect,
      keywords: c.keywords,
    })),
    mages: [],
    nemeses: [],
  }));

  const banner = `// AUTO-GENERATED by scripts/build-data.ts — DO NOT EDIT.\n// Source: data/expansions/*.yaml\n`;
  const body = `import type { Expansion } from '../types';\n\nexport const EXPANSIONS: Expansion[] = ${JSON.stringify(data, null, 2)} as const satisfies Expansion[];\n`;

  mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, banner + body, 'utf8');

  const totalCards = data.reduce((n, e) => n + e.cards.length, 0);
  console.log(
    `[build-data] 生成完了: ${expansions.length} 拡張 / ${totalCards} カード → ${path.relative(ROOT, OUT_FILE)}`,
  );
}

main();
